# Generated by Django 4.2.5 on 2023-09-14 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_user_cash_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='stock_symbol',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cash',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=10),
        ),
    ]
