# Generated by Django 4.2.7 on 2023-11-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_remove_user_cash_user_avatar_user_bio_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='static/avatar.svg', null=True, upload_to=''),
        ),
    ]
