# Generated by Django 4.2.5 on 2023-09-15 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_user_quantity_user_stock_symbol_alter_user_cash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='user',
            name='stock_symbol',
        ),
    ]
