# Generated by Django 4.2.7 on 2023-11-21 14:55

from django.db import migrations, models
import register.models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='static/imgs/avatar.png', null=True, upload_to=register.models.user_avatar_path),
        ),
    ]
