# Generated by Django 4.2.5 on 2023-09-15 00:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0003_stocks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stocks',
            new_name='UsersStocks',
        ),
    ]
